name: Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
env:
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  PUSH_TO_DOCKER_HUB: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - run: echo "The event name is ${{ github.event_name }}"
      - name: Generate tags
        id: generate_tags
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          IMAGE="michaellutaaya/github-actions-example"
          echo ::set-output name=tagged_image::${IMAGE}:${TAG}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with: 
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Log in to Docker Hub
        if: env.PUSH_TO_DOCKER_HUB == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: .dockerdev/Dockerfile
          push: ${{ env.PUSH_TO_DOCKER_HUB == 'true' }}
          tags: ${{ steps.generate_tags.outputs.tagged_image }}
          target: production
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
