name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
      - name: Start containers
        run: docker-compose -f docker-compose.yml up -d
      - name: Prepare database
        run: docker-compose exec -T web bin/rails db:prepare
      - name: Run RSpec
        run: docker-compose exec -T web bin/rails spec
